name: insta_clone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  chat_bubbles: ^1.7.0
  flutter_bloc: ^9.0.0
  text_scroll: ^0.2.0
  lottie: ^3.3.1
  gif: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  skeletonizer: ^1.4.3
  video_player: ^2.9.3
  readmore: ^3.0.0
  sqflite: ^2.4.1
  permission_handler: ^11.4.0
  photo_manager: ^3.6.4
  camera: ^0.11.1
  get: ^4.7.2
  flutter_flavor: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/gif/
    - assets/post/
    - assets/jpeg/
    - assets/png/
    - assets/jpg/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/icons/flutter-icons-cfa10b21/fonts/MyFlutterApp.ttf
